name: pocket_option_expert
description: Pocket Option Expert
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.6.1
  json_serializable: ^6.6.1
  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  hive: ^2.2.3
  bloc: ^8.1.0
  path_provider: ^2.0.12
  json_annotation: ^4.8.0
  flutter_svg_provider: ^1.0.3
  page_transition: ^2.0.9
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.9
  flutter_svg: ^1.1.6

dev_dependencies:
  dart_code_metrics: ^5.4.0
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  ios: true
  image_path: "assets/images/app_icon.png"


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800

